AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  productsapi-intellij

  Sample SAM Template for productsapi-intellij

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Runtime: java11

Resources:
  ProductsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Products
      PrimaryKey:
        Name: id
        Type: Number
  CreateProductFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: productsapi
      Handler: com.aws.apis.productsapi.CreateProductLambda::createProduct
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Products
      Events:
        ProductEvents:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /products
            Method: POST

