version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customersapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1gjfn5upkdfqd"
s3_prefix = "customersapi"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
